### ISSUE TITLE
Allow basic filtering.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#1017]
Examples I think should be valid:

```
editor:
  models:
    project:
      - archive
      - where:
        - archived_at: nil
```

Would be like: `can :archive, Project, [all the other magic], archived_at: nil`

```
editor:
  models:
    project:
      - archive
      - where:
        - workspace:
          - archived_at: nil
```

Would be like: `can :archive, Project, [all the other magic], workspace: {archived_at: nil}`
