### ISSUE TITLE
Allow `manage` minus `destroy` or minus some specific actions?

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#1018]
What I think should be valid examples:

```
editor:
  models:
    project:
      - manage
      - not: destroy
```

```
editor:
  models:
    project:
      - manage
      - not: 
        - destroy
```
