### ISSUE TITLE
Implement dark-mode support on Trix buttons.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#214]
Let's follow up https://github.com/bullet-train-co/bullet_train-core/pull/207 with whatever work is required to make dark-mode actually look right.

**Comment by gazayas** [comment]
This one's giving me some trouble too, but I'll post an update.

The [original repository](https://github.com/basecamp/trix) uses svgs which you can find [here](https://github.com/basecamp/trix/tree/main/assets/trix/images). Since the svg code isn't inline, we have to override the `background-image` property like [this comment](https://github.com/basecamp/trix/issues/464#issuecomment-564683997):
```CSS
.trix-button--icon-bold::before {
  background-image: url('data:image/svg+xml;utf-8,<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 1024 1024"><path fill="%23777777" d="M697.8 481.4c33.6-35 54.2-82.3 54.2-134.3v-10.2C752 229.3 663.9 142 555.3 142H259.4c-15.1 0-27.4 12.3-27.4 27.4v679.1c0 16.3 13.2 29.5 29.5 29.5h318.7c117 0 211.8-94.2 211.8-210.5v-11c0-73-37.4-137.3-94.2-175.1zM328 238h224.7c57.1 0 103.3 44.4 103.3 99.3v9.5c0 54.8-46.3 99.3-103.3 99.3H328V238zm366.6 429.4c0 62.9-51.7 113.9-115.5 113.9H328V542.7h251.1c63.8 0 115.5 51 115.5 113.9v10.8z"></path></svg>');
}
```

This is fine, the problem comes when trying to apply it to dark mode only.

According to [Tailwind's docs](https://tailwindcss.com/docs/background-image#customizing-your-theme), you can use a custom background image like this:
```JavaScript
module.exports = {
  theme: {
    extend: {
      backgroundImage: {
        'hero-pattern': "url('/img/hero-pattern.svg')",
        'footer-texture': "url('/img/footer-texture.png')",
      }
    }
  }
}
```

I want to combine this with something like `@apply dark:bg-bold-icon`, but Tailwind can't seem to find the image I downloaded locally with `url()`. I'll submit a PR if I make any progress.

**Comment by gazayas** [comment]
I think I'm just going to go with vanilla CSS on this one:

```CSS
@media (prefers-color-scheme: dark) {
  .trix-button--icon-bold::before {
    background-image: url('data:image/svg+xml;utf-8,<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 1024 1024"><path fill="%23FFFFFF" d="M697.8 481.4c33.6-35 54.2-82.3 54.2-134.3v-10.2C752 229.3 663.9 142 555.3 142H259.4c-15.1 0-27.4 12.3-27.4 27.4v679.1c0 16.3 13.2 29.5 29.5 29.5h318.7c117 0 211.8-94.2 211.8-210.5v-11c0-73-37.4-137.3-94.2-175.1zM328 238h224.7c57.1 0 103.3 44.4 103.3 99.3v9.5c0 54.8-46.3 99.3-103.3 99.3H328V238zm366.6 429.4c0 62.9-51.7 113.9-115.5 113.9H328V542.7h251.1c63.8 0 115.5 51 115.5 113.9v10.8z"></path></svg>') !important;
  }
}
```
