### ISSUE TITLE
Add `automatic_documentation_for`

### ISSUE THREAD

**Issue by newstler** [bullet-train-co/bullet_train-core#763]
We need 
````yaml
tags:
  - name: Team
    description:
      $ref: docs/team_description.md
````
to automatically merge those description markdown files into main `openapi.yaml` file, as we do now with [`redocly bundle`](https://redocly.com/docs/cli/commands/bundle/).

So the proposal is to add `automatic_documentation_for` to OpenApiHelper so it replaces redocly's functionality.
