### ISSUE TITLE
Localized dates / time for `shared/attributes/date_and_time`

### ISSUE THREAD

**Issue by lcorneliussen** [bullet-train-co/bullet_train-core#980]
Dates helper hard-references multiple date formats, which would be nice to have localizable.

* `%B %-d` for same year
* `%B %-d, %Y` for different year
* `%l:%M %p` for time
* `Today at {time}` as date replacement for today
* `Yesterday at  {time}` as date replacement for yesterday
* `{date} at {time}` for date/time combination

Also `t('global.formats.timestamp_unavailable')` is used as a fallback if there is no timestamp.

Changes proposed:
* Use `global.dates.today` for today
* Add `global.dates.yesterday` for yesterday
* Move Today/Yesterday to date_format and use `timestamp_date_and_time` to combine date and time
* Add `%B %-d, %Y` as `formats.date_long` and `%B %-d` as formats.date_long_without_year
* Add `%l:%M %p`as `formats.time`

```yaml
    dates:
      today: Today
+      yesterday: Yesterday
      day:
        one: 1 Day
        other: '%{count} Days'
      last_month: Last Month
      last_week: Last Week
      last_day:
        one: Last Day
        other: Last %{count} Days
    formats:
      timestamp_unavailable: Never
+      timestamp_date_and_time: '%{date} at %{time}'
      date: '%m/%d/%Y'
      date_and_time: '%m/%d/%Y %l:%M %p'
+      time: '%l:%M %p'
+      date_long: '%B %-d, %Y'
+      date_long_without_year: '%B %-d'
```

Relevant files:
* https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-fields/app/helpers/account/dates_helper.rb
* https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-themes/app/views/themes/base/attributes/_date_and_time.html.erb
* https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train/config/locales/en/base.yml
